#!/bin/bash
curl -s 'https://www.us-proxy.org/' > us.html;
cat us.html 			     | 
grep -oP '(?<=td>)[^</td>]*' | 
sed 's/[A-Za-z]*//g' 		 | 
sed -e '{:q;N;s/\n/ /g;t q}' | 
sed 's/ /:/g' 				 | 
sed -e 's/:::/\\\n /g' 		 | 
sed -e 's/::/\\\n /g' 		 | 
sed 's/\ //g' 				 | 
sed 's/\\//g' 				 | 
sed '/^$/d' > /var/www/html/strip/us.txt;
truncate -s-2 /var/www/html/strip/us.txt;
rm -rf us.html;
